name: todo
description: A new Flutter project.
version: 1.1.1+20191101

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0-nullsafety.0
  # objectdb: ^1.0.5
  path_provider: ^2.0.9
  json_annotation: ^4.0.1
  sqflite: ^2.0.0+3
  flutter_colorpicker: ^1.0.3
  intl: ^0.17.0
  flutter_markdown: ^0.6.2
  cupertino_icons: ^1.0.3
  sqflite_common_ffi:
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
flutter:
  uses-material-design: true